qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 1
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 2
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 4
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 8
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 16
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 32
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 64
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 128
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 256
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 512
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 1024
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 2048
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 4096
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 8192
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 16000
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 32000
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 64000
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 128000
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 256000
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 512000
qsub -m a -M flipperkid@gmail.com -cwd -b y -j y -q core2-quad.q -pe threaded 4 ./script_test.sh 1024000
